### ISSUE TITLE
Doesn't work for this example

### ISSUE THREAD

**Issue by jolic** [KunihikoKido/atom-json-converter#1]
Hi,

I've tried the plugin but it doesn't work for this example:

```
id,"Konto","TYPA","TYPB","TYPC","TYPD","Beschreibung"
1,"0001","S","B","","","Test A"
2,"0002","S","B","","","Test B"
3,"0015","S","B","","","Test C"
4,"0020","S","B","","","Test D"
5,"0025","S","B","","","Test E"
```

The new document contains `[]`

Any hints on this?

**Comment by KunihikoKido** [comment]
Hi

Check the following steps:
1. Package json-converter package, v0.2.0
2. Write the sample data to the active editor.
3. While editor is active, run the `Json Converter: Csv to Json` command.
