### ISSUE TITLE
CRLF delimited csv-json conversion

### ISSUE THREAD

**Issue by fhisa** [KunihikoKido/atom-json-converter#2]
About converting CSV to JSON, when line delimiter of input was **CRLF**, the tail of last key string appended an extra character "\r".

``` csv
name, age
Tanaka, 20
```

``` json
[
  {
    "name": "Tanaka",
    " age\r": " 20"
  }
]
```

**Comment by KunihikoKido** [comment]
Supported by v0.2.1. Please try it!

**Comment by fhisa** [comment]
thank you!
