### ISSUE TITLE
Nested JSON

### ISSUE THREAD

**Issue by DeysonOrtiz** [KunihikoKido/atom-json-converter#3]
Hello.  It seems I am not able to get nested Json information converted to CSV.  Please advice.

**Comment by KunihikoKido** [comment]
Example by v0.2.3

_Settings:_
- CSV Delimiter: `\t`
- CSV Delimiter Array: `,`

_Nested JSON:_

``` json
[
  {
    "id": "001",
    "colors": [
      {"color": "red", "value": "#f00"},
      {"color": "green","value": "#0f0"}
    ]
  },
  {
    "id": "002",
    "colors": [
      {"color": "blue", "value": "#00f"},
      {"color": "cyan", "value": "#0ff"}
    ]
  }
]
```

Convert to ... (Run the `Json Converter: Json To Csv` command)

_CSV (TSV):_

``` csv
id  colors
001 [{"color":"red","value":"#f00"},{"color":"green","value":"#0f0"}]
002 [{"color":"blue","value":"#00f"},{"color":"cyan","value":"#0ff"}]
```

**Comment by DeysonOrtiz** [comment]
Thank you very much for your valuable time. I will give it a try.  Thank you again. Keep up the great work and have a beautiful day! :)
